__all__ = ["sum_as_string", "AutoPlay", "FooStruct"]

def sum_as_string(a: int, b: int) -> str:
    pass

class FooStruct:
    def increment(self) -> None: ...
    def add(self, value: int) -> None: ...
    def get_count(self) -> int: ...

class AutoPlay:
    @staticmethod
    def connect(serial: str) -> "AutoPlay": ...
    def is_screen_on(self) -> bool: ...
    def ensure_screen_on(self) -> None: ...
    def get_abi(self) -> str: ...
    def get_sdk(self) -> str: ...
    def click(self, x: int, y: int) -> None: ...
    def screencap(self) -> bytes:
        """
        Capture the screen and return the image data as PNG bytes.
        """
        ...
